# -*- coding: utf-8 -*-
"""
Created on Mon Jan 23 01:23:45 2023

@author: suric
"""
import logging
import openai
import parameters


class SentenceGenerator():
    '''The main class for the core generation of phrases.
    Here we use openai's api.
    This has to be updated relatively often as OpenAI releases new models,
    as they then change what language model they make available through their api.'''
    _logger=logging.getLogger(__name__)
    _logger.setLevel(20)
    _logger.addHandler(
        logging.FileHandler(filename='sentence_generator.log', encoding='utf-8', mode='w')
        )

    sentencesperquery=10
    sequencelength=25
    topp=0.9
    topk=3
    shorttermmemory_size=20
    # stoptokens= [17,503,4,1926,34,2040] #?!. end of message detection tokens.
    # stopcriteria= generation_stopping_criteria.StoppingCriteriaList()
    # stopcriteria.append(StopWordCriteria(stoptokens))
    context = []


    def __init__(self, sentencesperquery:int,sequencelength:int,shorttermmemory_size:int,topp:float,topk:int):
        openai.api_key=parameters.openai_api_key
        self.sentencesperquery=sentencesperquery
        self.sequencelength=sequencelength
        self.shorttermmemory_size=shorttermmemory_size
        self.topp=topp
        self.topk=topk


    def generate_sentences(self,system_prompt : list , prompt: str ,*context: dict):
        """Here we do the main call to openAI.

        Args:
            system_prompt (str): phrases to indicate how Malkuth should behave.
            prompt (dict ): message : Phrase adressed to Malkuth. 
                        messagesender :  the name of the interlocutor. 

        Returns:
            *sentences : choices generated by the openai language model.
        """
        sentences = []

        query = [
                {
                  "role": "system",
                  "content": [
                    {
                      "type": "text",
                      "text": sys_prompt
                    }
                  ]
                } for sys_prompt in system_prompt
                ]

        query += list(context)
        query += [self.parse_message(prompt['message'],username=prompt['messagesender'] )]

        self._logger.info(str(query))

        for _ in range(self.sentencesperquery):

            response = openai.chat.completions.create(
                model="gpt-4o-mini-2024-07-18",
                messages= query,
                temperature=0.4,
                max_tokens=self.sequencelength*4,
                top_p=self.topp,
                frequency_penalty=0,
                presence_penalty=0
                )

            self._logger.info(str(response))
            sentences.append(response.choices[0].message.content)


            #print(sentenceb)

        return sentences


    def inference_session(self,system_prompt : list,prompt: dict,last_question : dict,last_response: str):
        '''We handle the short term memorisation of past messages here.
        '''
        if last_question and last_response:
            self.context.append(self.parse_message(last_question['message'],
                                                    username= last_question['messagesender']))
            self.context.append(self.parse_message(last_response,role='assistant'))

        if len(self.context)>self.shorttermmemory_size:
            self.context.pop(0)
            self.context.pop(0)

        gscent = self.generate_sentences(system_prompt,prompt, *self.context)

        return gscent


    def parse_message(self, text : str , role : str = 'user', username : str=''):
        '''Parse string message into open ai formatted message'''
        message = {
            "role": role,
            "content": [
                {
                "type": "text",
                "text" : text
                }
            ]
            }
        if username :
            message['name'] = username

        return message

    def free_text_gen(self,prompt, system_prompt=''):
        '''place the burden of indicating context on the user, no memory whatsoever'''
        if not system_prompt:
            system_prompt = self.default_metacontext

        response = self.client.chat.completions.create(
            model="gpt-4o-mini-2024-07-18",
            messages=[
                {
                  "role": "system",
                  "content": [
                    {
                      "type": "text",
                      "text": system_prompt
                    }
                  ]
                },
                self.parse_message(prompt)
                ],
            temperature=0.4,
            max_tokens=self.sequencelength,
            top_p=self.topp,
            frequency_penalty=0,
            presence_penalty=0
            )
        return response.choices[0].message.content

    def wipeshorttermmemory(self):
        self.context = []
